apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-deploy
  template:
    metadata:
      labels:
        app: cart-deploy
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
